apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-jenk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-jenk
  template:
    metadata:
      labels:
        app: kube-jenk
    spec:
      containers:
        - name: kube-jenk
          image: aravind2003/kube-jenk:1.0   # Jenkins will replace this
          ports:
            - containerPort: 3000
